# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Far Horizon OÜ Policies
email: hello@farhorizons.io
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Far Horizon OÜ's official policy portal. Here, you'll find all the necessary
  information regarding our terms of service, privacy policy, refund and cancellation policies,
  and guidelines on restricted use. Our aim is to maintain transparency and ensure that our
  policies are clear, fair, and easily accessible to all our users. Navigate through our site
  to find detailed explanations on how we protect your data, how you can manage your account,
  and our commitment to creating a safe and respectful environment for everyone.
baseurl: "/policies" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username: jekyll

policies_github_url: https://github.com/far-horizons-ou/policies
company_url: https://farhorizons.io
company_name: Far Horizon OÜ
company_address: "Sepapaja 6, Tallinn, 15551, Estonia"
report_email: report@farhorizons.io
privacy_email: privacy@farhorizons.io
appeals_email: appeals@farhorizons.io

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-relative-links
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
